##
# Makefile automatically generated by genmake 1.0, Jan-24-03
# genmake 1.0 by muquit@lucent.com
##
CC= gcc
DEFS= -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_TIME_H=1 -DHAVE_CTYPE_H=1 -DSTDC_HEADERS=1
PROGNAME= hod
INCLUDES=  -I.
LIBS=
BINDIR = /usr/bin
MANPAGE = doc/hod.1.gz
MANDIR = /usr/share/man/man1
README=README.md
MAIN_MD=./docs/README.md
GLOSSARY_FILE=./docs/glossary.txt
MARKDOWC_TOC=markdown-toc-go

# replace -O with -g in order to debug

DEFINES= $(INCLUDES) $(DEFS) -DSYS_UNIX=1
CFLAGS= -O $(DEFINES)

SRCS = hod.c

OBJS = hod.o

.c.o:
	rm -f $@
	$(CC) $(CFLAGS) -c $*.c

all: $(PROGNAME)

$(PROGNAME) : $(OBJS)
	$(CC) $(CFLAGS) -o $(PROGNAME) $(OBJS) $(LIBS)

install:
	@cp $(PROGNAME) $(BINDIR)
	@cp $(MANPAGE) $(MANDIR)

deb:
	@ruby ./mk_debian_package.rb

doc:
	@ruby ./mk_doc.rb
	echo "*** Generating README.md with TOC ..."
	touch $(README)
	chmod 600 $(README)
	$(MARKDOWC_TOC) -i $(MAIN_MD) -o $(README) --glossary ${GLOSSARY_FILE} -f
	chmod 444 $(README)


clean:
	rm -f $(OBJS) $(PROGNAME) core
